package me.pauleff.handlers;

import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

/**
 * Handles UUID-related actions, including conversions between online and offline UUIDs.
 * Uses Mojang's API for retrieving UUIDs and names from online services.
 *
 * @author Paul Ferlitz
 */
public class UUIDHandler {
    private static final Logger LOGGER = LoggerFactory.getLogger(UUIDHandler.class);
    private static final HTTPHandler HTTP = new HTTPHandler();
    private static final String apiBasePath = "https://api.mojang.com/";

    /**
     * Converts a player name to an offline UUID.
     * How to do this was documented <a href="https://www.spigotmc.org/threads/how-uuid-is-generated-for-offline-mode-nicknames.347835/">here</a> on the SpigotMC forums by user md_5.
     *
     * @param name The player's name.
     * @return The resulting {@link UUID}.
     */
    public static UUID offlineNameToUUID(String name) {
        UUID uuid = UUID.nameUUIDFromBytes(("OfflinePlayer:" + name).getBytes(StandardCharsets.UTF_8));
        LOGGER.info("Offline UUID generated for '{}': {}", name, uuid);
        return uuid;
    }

    /**
     * Converts a player name to an online UUID by querying Mojang's API.
     *
     * @param name The player's name.
     * @return The resulting {@link UUID}.
     * @throws IOException If a connection issue occurs.
     */
    public static UUID onlineNameToUUID(String name) throws IOException {
        HTTP.set(apiBasePath + "users/profiles/minecraft/" + name);
        String response = HTTP.get();

        if (response == null || response.isEmpty()) {
            LOGGER.warn("No UUID found for online player '{}'.", name);
            return null;
        }
        // Extract the UUID from the response
        JSONObject json = new JSONObject(response);
        String uuid = json.optString("id", "").replaceAll(
                "(\\w{8})(\\w{4})(\\w{4})(\\w{4})(\\w{12})", "$1-$2-$3-$4-$5");
        // Check if the UUID is valid
        if (uuid.isEmpty()) {
            LOGGER.warn("Invalid UUID retrieved for name '{}'.", name);
            return null;
        }

        LOGGER.info("Retrieved online UUID for player '{}': {}", name, uuid);
        return UUID.fromString(uuid);
    }

    /**
     * Retrieves a player's name from their online {@link UUID} using Mojang's Session Server.
     * * @param uuid The player's {@link UUID}.
     * @return The player's name, or null if the player is not found/offline.
     * @throws IOException If a connection or rate-limiting issue occurs.
     */
    public static String onlineUUIDToName(UUID uuid) throws IOException {
        // 1. Use the Session Server (requires dashes, which uuid.toString() provides)
        String url = "https://sessionserver.mojang.com/session/minecraft/profile/" + uuid.toString();

        HTTP.set(url);
        String response = HTTP.get();

        // 2. Check for empty response (Mojang returns 204 No Content for unknown UUIDs)
        if (response == null || response.isEmpty()) {
            LOGGER.warn("No profile found for UUID '{}'. This may be an offline/cracked UUID.", uuid);
            return null;
        }

        try {
            JSONObject json = new JSONObject(response);

            // 3. Extract the name field
            String name = json.optString("name", "");

            if (name.isEmpty()) {
                LOGGER.warn("Response for UUID '{}' did not contain a name.", uuid);
                return null;
            }

            LOGGER.info("Successfully retrieved name: {} for UUID: {}", name, uuid);
            return name;

        } catch (Exception e) {
            LOGGER.error("Failed to parse Mojang API response for UUID: {}", uuid, e);
            return null;
        }
    }

    public enum UUIDType {
        ONLINE,   // Version 4
        OFFLINE,  // Version 3
        INVALID   // Anything else
    }

    /**
     * Determines if a given {@link UUID} is online or offline
     * or offline (generated by the server).
     *
     * @param uuid The {@link UUID} to check.
     * @return True if the {@link UUID} is online, false otherwise.
     */
    public static UUIDType getUUIDType(UUID uuid) {
        int v = uuid.version();
        if (v == 4) return UUIDType.ONLINE;
        if (v == 3) return UUIDType.OFFLINE;
        return UUIDType.INVALID;
    }

//    /**
//     * Converts an online UUID to an offline UUID by first retrieving the player's name.
//     *
//     * @param onlineUUID The player's online {@link UUID}.
//     * @return The player's offline {@link UUID}, or null if conversion fails.
//     * @throws IOException If a connection issue occurs.
//     */
//    public static UUID onlineUUIDToOffline(UUID onlineUUID) throws IOException {
//        String playerName = onlineUUIDToName(onlineUUID);
//        if (playerName == null) {
//            LOGGER.error("Failed to convert online UUID '{}' to offline (no name found).", onlineUUID);
//            return null;
//        }
//        return offlineNameToUUID(playerName);
//    }
}
